# Generated by Django 5.2.8 on 2025-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversationfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationfile',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
